[package]
name = "rtrs"
version = "0.1.0"
authors = ["Liu Shiqi <liushiqi17@mails.ucas.ac.cn>"]
edition = "2018"

[dependencies]
nalgebra = "0.16.12"
image = "0.20.1"
rand = "0.6.1"
clap = "2.32.0"
serde = "1.0.82"
serde_yaml = "0.8.8"
