[package]
name = "rtrs"
version = "0.1.0"
authors = ["Liu Shiqi <liushiqi17@mails.ucas.ac.cn>"]
description = "A simple ray tracing program written in rust based on *Ray Tracing In A Week*"
edition = "2018"

[dependencies]
image = "0.20.1"
rand = "0.6.1"
rayon = "1.0.3"
cgmath = "0.16.1"
